version: '3'
services:
  consul:
    image: hashicorp/consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    
  fabio:
    image: fabiolb/fabio
    ports:
      - "9999:9999" # Fabio HTTP port
      - "9998:9998" # Fabio UI port
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    depends_on:
      - consul

  orchestrator:
    build: .
    container_name: orchestrator
    expose:
      - "8090"
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
    depends_on:
      - consul
      - fabio