services:
  consul:
    image: hashicorp/consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    networks:
      - fabio_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - fabio_network
    restart: unless-stopped

  fabio:
    image: fabiolb/fabio
    ports:
      - "9999:9999"  # Fabio HTTP port
      - "9998:9998"  # Fabio UI port
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    depends_on:
      - consul
    networks:
      - fabio_network

  orchestrator:
    build: .
    container_name: orchestrator
    user: root
    group_add:
      - "0"
    expose:
      - "8090"
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - BEHIND_PROXY=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - consul
      - fabio
    networks:
      - fabio_network

  swag:
    image: linuxserver/swag
    container_name: swag
    restart: unless-stopped
    profiles: ["production"]
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=operator.tryiris.dev
      - VALIDATION=http
      - SUBDOMAINS=www,admin,rabbitmq
      - DISABLE_IPV6=true
      - EMAIL=shanur.cse.nitap@gmail.com    # Add this line for Let's Encrypt notifications
    volumes:
      - ./swag:/config
    networks:
      - fabio_network
    # Add these lines
    cap_add:
      - NET_ADMIN

networks:
  fabio_network:
    name: fabio_network
    external: true

volumes:
  letsencrypt_data:
  rabbitmq-data:
