services:
  consul:
    image: hashicorp/consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    networks:
      - fabio_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - fabio_network
    restart: unless-stopped

  fabio:
    image: fabiolb/fabio
    ports:
      - "9999:9999"  # Fabio HTTP port
      - "9998:9998"  # Fabio UI port
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    depends_on:
      - consul
    networks:
      - fabio_network

  orchestrator:
    build: .
    container_name: orchestrator
    expose:
      - "8090"
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - BEHIND_PROXY=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - consul
      - fabio
    networks:
      - fabio_network

  swag:
    image: linuxserver/swag
    container_name: swag
    restart: unless-stopped
    profiles: ["production"]
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUID=1000             # Set to your user id
      - PGID=1000             # Set to your group id
      - TZ=Europe/London      # Adjust timezone as needed
      - URL=bua.tryiris.dev   # Your primary domain name
      - VALIDATION=http       # Use HTTP validation (or dns if you prefer)
      - SUBDOMAINS=www,rabbitmq # Subdomains to be covered by the cert
      - DISABLE_IPV6=true    # Disable IPv6 support
    volumes:
      - letsencrypt_data:/config
      - ./swag/nginx/site-confs:/config/nginx/site-confs
    networks:
      - fabio_network

networks:
  fabio_network:
    driver: bridge

volumes:
  letsencrypt_data:
