services:
  consul:
    image: hashicorp/consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
    networks:
      fabio_network:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      fabio_network:
    restart: unless-stopped

  fabio:
    image: fabiolb/fabio
    ports:
      - "9999:9999"  # Fabio HTTP port
      - "9998:9998"  # Fabio UI port
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    depends_on:
      - consul
    networks:
      fabio_network:

  orchestrator:
    build: .
    container_name: orchestrator
    user: root
    group_add:
      - "0"
    expose:
      - "8090"
    environment:
      - CONSUL_HTTP_ADDR=consul:8500
      - BEHIND_PROXY=true
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - consul
      - fabio
    networks:
      fabio_network:

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    profiles: ["production"]
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Europe/London
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config:/etc/traefik
      - ./traefik/letsencrypt:/letsencrypt
    networks:
      fabio_network:
    command:
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=shanur.cse.nitap@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`admin.operator.tryiris.dev`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=myresolver"

networks:
  fabio_network:
    external: true

volumes:
  letsencrypt_data:
  rabbitmq-data:
