services:
  chromium:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: chromium
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CHROME_CLI=https://www.linuxserver.io/ #optional
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 3001:3001
      - 9222:9222
    shm_size: "2gb"
    restart: unless-stopped